package consts

const (
	HOST       = "HOST"
	PORT       = "PORT"
	API_PREFIX = "API_PREFIX"
	NODE_ENV   = "NODE_ENV"
	APP_NAME   = "APP_NAME"
)

const (
	MYSQL_HOST     = "MYSQL_HOST"
	MYSQL_PORT     = "MYSQL_PORT"
	MYSQL_USER     = "MYSQL_USER"
	MYSQL_PASSWORD = "MYSQL_PASSWORD"
	MYSQL_DB_NAME  = "MYSQL_DB_NAME"
)

const (
	RATE_LIMIT_OF_MINUTE = "RATE_LIMIT_OF_MINUTE"
)

const (
	REDIS_STORE_HOST = "REDIS_STORE_HOST"
	REDIS_STORE_PORT = "REDIS_STORE_PORT"
)
